### ISSUE TITLE
AttributeError: module 'subprocess' has no attribute 'mswindows' with Python3.5

### ISSUE THREAD

**Issue by woolgathering** [Abjad/abjad#526]
Unable to build a score with Python 3.5.  Same script works with 2.7, however.  I'm on OS X 10.10.3.

Error thrown is:
`AttributeError: module 'subprocess' has no attribute 'mswindows'`

Found the line in question at 213 in AbjadConfiguration.py.  It can be made to work if the lilypond_version_string is hardcoded, but the entire process runs much slower than if 2.7 is used.

**Comment by josiah-wolf-oberholtzer** [comment]
This was fixed in July: https://github.com/Abjad/abjad/commit/28ba5b7fea1decfa400a88e5a15def51bc57b80a#diff-7ec39bc6f200983255396cf250663af3L217
