### ISSUE TITLE
documentationtools.Pipe does not work on OSX's Python 2.7

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#207]
_From [josiah.oberholtzer](https://code.google.com/u/josiah.oberholtzer/) on February 19, 2013 18:09:20_

Apple's precompiled Python is missing select.poll():

$ python2.6
Python 2.6.1 ( r261 :67515, Jun 24 2010, 21:47:49)
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> select.poll()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'poll'

This renders our two-way, non-blocking pipe implementation inoperative.

It should be rewritten to work on any platform (within reason).

_Original issue: http://code.google.com/p/abjad/issues/detail?id=206_

**Comment by josiah-wolf-oberholtzer** [comment]
Issue is moot.

`documentationtools.Pipe` was removed during 2.17 development.
